-- P2P call billing: free minutes bucket + call analytics
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "freeMinutes" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "callerUserId" INTEGER;
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "receiverUserId" INTEGER;
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "minutesBilled" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "freeMinutesUsed" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "walletDebited" DOUBLE PRECISION NOT NULL DEFAULT 0;
